{application,facebook,
             [{description,"Facebook Graph API Wrapper written in Elixir.\nPlease note, this is very much a work in progress. Feel free to contribute using pull requests.\n"},
              {modules,['Elixir.Facebook','Elixir.Facebook.Config',
                        'Elixir.Facebook.GraphAPI',
                        'Elixir.Facebook.GraphVideoAPI',
                        'Elixir.Facebook.ResponseFormatter',
                        'Elixir.Facebook.Stream']},
              {registered,[]},
              {vsn,"0.18.0"},
              {mod,{'Elixir.Facebook',[]}},
              {applications,[kernel,stdlib,elixir,httpoison,json,logger]},
              {env,[{env,dev},
                    {graph_url,<<"https://graph.facebook.com">>},
                    {graph_video_url,<<"https://graph-video.facebook.com">>},
                    {app_secret,nil},
                    {app_id,nil},
                    {app_access_token,nil}]}]}.
